- name: install packages
  apt:
    name:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    
- name: Add Docker official GPG key
  shell: if [ -e /etc/apt/keyrings/docker.gpg ] ;then echo "Exist GPG skip" ;else curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg ;fi

- name: set up the repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    
- name: Update
  apt:
    name: "*"
    state: latest
    update_cache: true

- name: install packages
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  ignore_errors: yes

### docker-compose
- name: Install docker-compose
  shell: curl -SL https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-composes

- name: chmod
  file:
    path: /usr/local/bin/docker-compose
    mode: '0777'
  ignore_errors: yes