- name: Purge the package "needrestart"
  apt:
    name: needrestart
    state: absent
    purge: true
    autoremove: yes

- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Tokyo
  become: true

- name: Time sync with rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: mirror set riken
  shell: sudo sed -i.bak -r 's!http://(security|us.archive).ubuntu.com/ubuntu!http://ftp.riken.jp/Linux/ubuntu!' /etc/apt/sources.list

- name: Update Upgrade
  apt:
    upgrade: yes
    update_cache: true

- name: set inputrc
  lineinfile:
    dest: /etc/inputrc
    insertafter: EOF
    line: '{{ item }}'
  with_items:
  - "set bell-style none"

- name: Add repository
  apt_repository:
    repo: 'ppa:apt-fast/stable'

- name: Update
  apt:
    update_cache: true

- name: install packages include aria2
  apt:
    name:
    - apt-fast
  ignore_errors: yes

- name: install packages
  apt:
    name:
    - bleachbit
  ignore_errors: yes

- name: install packages
  apt:
    name:
    - preload
  ignore_errors: yes

- name: set
  lineinfile:
    dest: /etc/default/preload
    backrefs: true
    insertafter: EOF
    regexp: '^#?\s*OPTIONS="-l /dev/null"'
    line: 'OPTIONS="-l /dev/null"'
  ignore_errors: yes

#- name: set
#  lineinfile:
#    dest: /etc/fstab
#    insertafter: EOF
#    line: '{{ item }}'
#  with_items:
#  - "tmpfs /tmp tmpfs defaults,noatime 0 0"
#  - "tmpfs /var/tmp tmpfs defaults,noatime 0 0"

- name: Remove "apparmor" package
  apt:
    name: apparmor
    state: absent

- name: remove
  file: 
    path: /etc/apparmor.d
    state: absent