- name: Purge the package "needrestart"
  apt:
    name: needrestart
    state: absent
    purge: true
    autoremove: yes

#- name: Set timezone to Asia/Tokyo
#  community.general.timezone:
#    name: Asia/Tokyo
#  become: true
#
#- name: Time sync with rsyslog
#  systemd:
#    name: rsyslog
#    state: restarted