- name: Purge the package "needrestart"
  become: true
  apt:
    name: needrestart
    state: absent
    purge: true
    autoremove: yes

- name: Set timezone to Asia/Tokyo
  become: true
  community.general.timezone:
    name: Asia/Tokyo

- name: Time sync with rsyslog
  systemd:
    name: rsyslog
    state: restarted